name: Playwright UI Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Build and Run SigLens
        run: |
          make build
          ./siglens --config server.yaml &
          sleep 10  # Give some time for SigLens to start

      - name: Install Playwright Dependencies
        run: |
          cd playwright-test
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          cd playwright-test
          npx playwright test