name: Playwright Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Build SigLens
      run: make build

    - name: Run SigLens
      run: make run &

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Playwright and dependencies
      run: |
        cd playwright-test
        npm ci
        npx playwright install --with-deps

    - name: Run Playwright tests
      run: |
        cd playwright-test
        npx playwright test